// Shared vocabulary for runtime format modules. Each runtime module owns its
// fields, resolution of layered settings, native target path, and rendering;
// this file only holds the helpers they have in common.

export const CORE_EFFORT = ['low', 'medium', 'high', 'xhigh', 'max']
// Plugin name in every manifest; hosts that namespace plugin skills expose a
// library skill as `agent-kit:<skill>` regardless of where it is installed.
export const PLUGIN_NAME = 'agent-kit'
export const ACCESS = ['read-only', 'edits', 'full']

export const oneLine = (value) => typeof value === 'string' && value.trim() === value && value.length > 0 && !/[\r\n]/.test(value)
export const stringList = (value) => Array.isArray(value) && value.every(oneLine) && new Set(value).size === value.length
export const choice = (values) => (value) => values.includes(value)
// Model availability belongs to the host or configured pool; only syntax is checked here.
export const modelName = (value) => value === null || oneLine(value)
export const positiveInteger = (value) => Number.isInteger(value) && value > 0
export const boolean = (value) => typeof value === 'boolean'
export const yamlList = (items) => `[${items.map((item) => JSON.stringify(item)).join(', ')}]`

export function validateFields(values, schema, origin) {
  if (!values || typeof values !== 'object' || Array.isArray(values)) throw new Error(`${origin} must be an object`)
  for (const [key, value] of Object.entries(values)) {
    if (!Object.hasOwn(schema, key)) throw new Error(`${origin}: unsupported field "${key}"`)
    if (!schema[key](value)) throw new Error(`${origin}: invalid ${key} ${JSON.stringify(value)}`)
  }
}

// Portable intent wins over a library runtime default; an explicit project
// runtime value wins over both. Every runtime resolves the same way.
export function layered(profile, project, portableValue, portableOverride, key) {
  if (project[key] !== undefined) return project[key]
  if (portableOverride) return portableValue
  return profile[key] ?? portableValue
}

const SOURCES_HEADING = '## Selected knowledge sources'
const INSTRUCTIONS_HEADING = '## Project instructions'
export const RESERVED_HEADINGS = [INSTRUCTIONS_HEADING, SOURCES_HEADING]

// Hosts choose a subagent by its description, and a project agent competes with
// the host's generic subagents. The description says when to prefer it, so the
// configured composition is used without prompting the parent to pick it. A
// project that routes delegation itself turns the hint off (`delegation_hint`).
export function delegationDescription(agent) {
  if (agent.delegationHint === false) return agent.description.trim()
  const base = agent.description.trim().replace(/[.\s]*$/, '.')
  return `${base} Project agent with the ${agent.profile} profession and this project's selected skills: use it proactively instead of a generic subagent for this work, including a narrower task inside it.`
}

// Project-specific rules (gates, forbidden paths, report language, read-first
// documents) follow the profession body and precede the knowledge sources.
export function projectInstructions(agent) {
  if (!agent.instructions) return ''
  return `\n\n${INSTRUCTIONS_HEADING}\n\n${agent.instructions.trim()}`
}

// Source locators. A library skill uses the host identifier each user's
// own installation resolves; a project skill uses its host catalog name when the
// host discovers that directory, else its project-relative path. No locator
// names a machine, user, or kit version.
export function skillLocator(runtime, { name, project, directory, relative }) {
  if (!project) return runtime.librarySkill(name)
  return runtime.discoveredSkillDirectories.includes(directory) ? name : relative
}

export const isSkillPath = (locator) => locator.includes('/')

export function knowledgeInstructions(sources, intro) {
  if (!sources.length) return ''
  return `\n\n${SOURCES_HEADING}\n\n${intro}\n\n${sources.map(({ name, path }) => `- ${name}: ${JSON.stringify(path)}`).join('\n')}`
}

// Split a rendered body into profession behavior, project instructions, and the
// selected-source list. Older targets appended a one-line skill instruction
// instead; treat it the same way.
export function splitKnowledge(text) {
  const sources = {}
  let body = text
  const index = body.indexOf(`\n\n${SOURCES_HEADING}`)
  if (index !== -1) {
    for (const match of body.slice(index).matchAll(/^- ([a-z0-9-]+): (".*")$/gm)) sources[match[1]] = JSON.parse(match[2])
    body = body.slice(0, index)
  }
  let instructions = ''
  const cut = body.indexOf(`\n\n${INSTRUCTIONS_HEADING}\n\n`)
  if (cut !== -1) {
    instructions = body.slice(cut + INSTRUCTIONS_HEADING.length + 4).trim()
    body = body.slice(0, cut)
  }
  body = body.trimEnd().replace(/\n\nBefore acting, read and follow these installed knowledge skills when relevant: [^\n]*\.$/, '')
  return { body: body.trimEnd(), instructions, sources }
}

const MARKER = /^(?:<!-- |# )Generated by agent-kit from (.+)\. Do not edit by hand\.(?: -->)?$/
const METADATA = /^(?:<!-- |# )agent-kit-metadata: (\{.*\})(?: -->)?$/

export function generatedComments(source, provenance, html = false) {
  const lines = [`Generated by agent-kit from ${source}. Do not edit by hand.`]
  if (provenance) lines.push(`agent-kit-metadata: ${JSON.stringify(provenance).replace(/-->/g, '--\\u003e')}`)
  return lines.map((line) => (html ? `<!-- ${line} -->` : `# ${line}`)).join('\n')
}

export function isGeneratedAgent(content) {
  return content.split('\n').slice(0, 20).some((line) => MARKER.test(line))
}

export function readProvenance(content) {
  for (const line of content.split('\n').slice(0, 30)) {
    const match = METADATA.exec(line)
    if (match) {
      try { return JSON.parse(match[1]) } catch { return undefined }
    }
  }
  return undefined
}

export function stripGeneratedComments(text) {
  return text.split('\n').filter((line) => !MARKER.test(line) && !METADATA.test(line)).join('\n').replace(/^\n+/, '')
}


const sameValue = (a, b) => JSON.stringify(a ?? null) === JSON.stringify(b ?? null)
const show = (value) => (value === undefined || value === null ? '(inherit/default)' : Array.isArray(value) ? value.join(', ') || '(none)' : String(value))

// Compare two parsed targets of one runtime. `kind` is the most significant
// difference: semantic (behavior, settings, skills), sources (where a selected
// skill is loaded from), provenance (metadata only), or none. Every kind except
// none is drift.
export function compareTargets(previous, next) {
  const changes = []
  if (previous.description !== next.description) changes.push('description changed')
  for (const key of new Set([...Object.keys(previous.settings), ...Object.keys(next.settings)])) {
    const before = previous.settings[key]
    const after = next.settings[key]
    if (sameValue(before, after)) continue
    if (Array.isArray(before) && Array.isArray(after)) {
      const added = after.filter((item) => !before.includes(item))
      const removed = before.filter((item) => !after.includes(item))
      changes.push(`${key}: ${[...added.map((item) => `+${item}`), ...removed.map((item) => `-${item}`)].join(' ') || 'order changed'}`)
    } else changes.push(`${key}: ${show(before)} → ${show(after)}`)
  }
  const addedSkills = next.skills.filter((skill) => !previous.skills.includes(skill))
  const removedSkills = previous.skills.filter((skill) => !next.skills.includes(skill))
  if (addedSkills.length || removedSkills.length) {
    changes.push(`skills: ${[...addedSkills.map((skill) => `+${skill}`), ...removedSkills.map((skill) => `-${skill}`)].join(' ')}`)
  }
  if (previous.body !== next.body) {
    const before = new Set(previous.body.split('\n'))
    const after = next.body.split('\n')
    changes.push(`profile behavior changed (${after.filter((line) => !before.has(line)).length} new or edited line(s))`)
  }
  if ((previous.instructions ?? '') !== (next.instructions ?? '')) changes.push('project instructions changed')
  const semantic = changes.length > 0
  const moved = next.skills.filter((skill) => previous.skills.includes(skill) && (previous.sources[skill] ?? null) !== (next.sources[skill] ?? null))
  for (const skill of moved) changes.push(`source for ${skill}: ${previous.sources[skill] ?? '(none)'} → ${next.sources[skill] ?? '(none)'}`)
  let metadata = false
  if (!previous.provenance) {
    if (next.provenance) changes.push('metadata: unknown baseline (no agent-kit-metadata)')
    metadata = Boolean(next.provenance)
  } else if (previous.provenance.kit !== undefined) {
    changes.push(`metadata: kit version ${previous.provenance.kit} no longer recorded`)
    metadata = true
  } else if (!sameValue(previous.provenance, next.provenance)) {
    changes.push('metadata: composition fingerprint changed')
    metadata = true
  }
  const kind = semantic ? 'semantic' : moved.length ? 'sources' : metadata ? 'provenance' : 'none'
  return { changes, kind }
}
