// Shared vocabulary for runtime format modules. Each runtime module owns its
// fields, resolution of layered settings, native target path, and rendering;
// this file only holds the helpers they have in common.

export const CORE_EFFORT = ['low', 'medium', 'high', 'xhigh', 'max']
export const ACCESS = ['read-only', 'edits', 'full']

export const oneLine = (value) => typeof value === 'string' && value.trim() === value && value.length > 0 && !/[\r\n]/.test(value)
export const stringList = (value) => Array.isArray(value) && value.every(oneLine) && new Set(value).size === value.length
export const choice = (values) => (value) => values.includes(value)
// Model availability belongs to the host or configured pool; only syntax is checked here.
export const modelName = (value) => value === null || oneLine(value)
export const positiveInteger = (value) => Number.isInteger(value) && value > 0
export const boolean = (value) => typeof value === 'boolean'
export const yamlList = (items) => `[${items.map((item) => JSON.stringify(item)).join(', ')}]`

export function validateFields(values, schema, origin) {
  if (!values || typeof values !== 'object' || Array.isArray(values)) throw new Error(`${origin} must be an object`)
  for (const [key, value] of Object.entries(values)) {
    if (!Object.hasOwn(schema, key)) throw new Error(`${origin}: unsupported field "${key}"`)
    if (!schema[key](value)) throw new Error(`${origin}: invalid ${key} ${JSON.stringify(value)}`)
  }
}

// Portable intent wins over a library runtime default; an explicit project
// runtime value wins over both. Every runtime resolves the same way.
export function layered(profile, project, portableValue, portableOverride, key) {
  if (project[key] !== undefined) return project[key]
  if (portableOverride) return portableValue
  return profile[key] ?? portableValue
}

const SOURCES_HEADING = '## Selected knowledge sources'
const SOURCES_INTRO = 'Use these source paths as the authoritative selected knowledge. If a body was not already loaded from its listed source, read it when relevant before acting; load linked references only as needed. Do not assume an unqualified skill name resolves to this installation.'

export function knowledgeInstructions(sources) {
  if (!sources.length) return ''
  return `\n\n${SOURCES_HEADING}\n\n${SOURCES_INTRO}\n\n${sources.map(({ name, path }) => `- ${name}: ${JSON.stringify(path)}`).join('\n')}`
}

// Split a rendered body into profession behavior and the selected-source list.
// Older targets appended a one-line skill instruction instead; treat it the same way.
export function splitKnowledge(text) {
  const sources = {}
  let body = text
  const index = body.indexOf(`\n\n${SOURCES_HEADING}`)
  if (index !== -1) {
    for (const match of body.slice(index).matchAll(/^- ([a-z0-9-]+): (".*")$/gm)) sources[match[1]] = JSON.parse(match[2])
    body = body.slice(0, index)
  }
  body = body.trimEnd().replace(/\n\nBefore acting, read and follow these installed knowledge skills when relevant: [^\n]*\.$/, '')
  return { body: body.trimEnd(), sources }
}

const MARKER = /^(?:<!-- |# )Generated by agent-kit from (.+)\. Do not edit by hand\.(?: -->)?$/
const METADATA = /^(?:<!-- |# )agent-kit-metadata: (\{.*\})(?: -->)?$/

export function generatedComments(source, provenance, html = false) {
  const lines = [`Generated by agent-kit from ${source}. Do not edit by hand.`]
  if (provenance) lines.push(`agent-kit-metadata: ${JSON.stringify(provenance).replace(/-->/g, '--\\u003e')}`)
  return lines.map((line) => (html ? `<!-- ${line} -->` : `# ${line}`)).join('\n')
}

export function isGeneratedAgent(content) {
  return content.split('\n').slice(0, 20).some((line) => MARKER.test(line))
}

export function readProvenance(content) {
  for (const line of content.split('\n').slice(0, 30)) {
    const match = METADATA.exec(line)
    if (match) {
      try { return JSON.parse(match[1]) } catch { return undefined }
    }
  }
  return undefined
}

export function stripGeneratedComments(text) {
  return text.split('\n').filter((line) => !MARKER.test(line) && !METADATA.test(line)).join('\n').replace(/^\n+/, '')
}

const sameValue = (a, b) => JSON.stringify(a ?? null) === JSON.stringify(b ?? null)
const show = (value) => (value === undefined || value === null ? '(inherit/default)' : Array.isArray(value) ? value.join(', ') || '(none)' : String(value))

// Compare two parsed targets of one runtime. `kind` is the most significant
// difference: semantic (behavior, settings, skills), paths (machine-local
// source locations only), provenance (kit version only), or none.
export function compareTargets(previous, next) {
  const changes = []
  if (previous.description !== next.description) changes.push('description changed')
  for (const key of new Set([...Object.keys(previous.settings), ...Object.keys(next.settings)])) {
    const before = previous.settings[key]
    const after = next.settings[key]
    if (sameValue(before, after)) continue
    if (Array.isArray(before) && Array.isArray(after)) {
      const added = after.filter((item) => !before.includes(item))
      const removed = before.filter((item) => !after.includes(item))
      changes.push(`${key}: ${[...added.map((item) => `+${item}`), ...removed.map((item) => `-${item}`)].join(' ') || 'order changed'}`)
    } else changes.push(`${key}: ${show(before)} → ${show(after)}`)
  }
  const addedSkills = next.skills.filter((skill) => !previous.skills.includes(skill))
  const removedSkills = previous.skills.filter((skill) => !next.skills.includes(skill))
  if (addedSkills.length || removedSkills.length) {
    changes.push(`skills: ${[...addedSkills.map((skill) => `+${skill}`), ...removedSkills.map((skill) => `-${skill}`)].join(' ')}`)
  }
  if (previous.body !== next.body) {
    const before = new Set(previous.body.split('\n'))
    const after = next.body.split('\n')
    changes.push(`profile behavior changed (${after.filter((line) => !before.has(line)).length} new or edited line(s))`)
  }
  const semantic = changes.length > 0
  const moved = next.skills.filter((skill) => previous.sources[skill] && next.sources[skill] && previous.sources[skill] !== next.sources[skill])
  if (moved.length) changes.push(`local source path changed for ${moved.join(', ')} (installation upgraded or moved)`)
  const before = previous.provenance?.kit ?? 'unknown baseline'
  const after = next.provenance?.kit
  const versionChanged = Boolean(after) && before !== after
  if (versionChanged) changes.push(`agent-kit: ${before} → ${after}`)
  const kind = semantic ? 'semantic' : moved.length ? 'paths' : versionChanged ? 'provenance' : 'none'
  return { changes, kind }
}
