direction: right
style.fill: transparent

shell: App Shell {class: interface}
ports: Environment Ports {class: interface}
modules: Game Modules {class: domain}
runtime: App Runtime {class: system}
shell -> ports: depends on
modules -> ports: depend on
runtime -> ports: implements
