direction: down
style.fill: transparent

PLAYER: {
  shape: sql_table
  id: string {constraint: primary_key}
  nickname: string
  status: string
}
GAME: {
  shape: sql_table
  id: string {constraint: primary_key}
  phase: string
  created_at: datetime
}
GAME_SEAT: {
  shape: sql_table
  player_id: string {constraint: foreign_key}
  game_id: string {constraint: foreign_key}
  stack: int
}
PLAYER.id <-> GAME_SEAT.player_id: occupies {
  source-arrowhead.shape: cf-one-required
  target-arrowhead.shape: cf-many
}
GAME.id <-> GAME_SEAT.game_id: contains {
  source-arrowhead.shape: cf-one-required
  target-arrowhead.shape: cf-many
}
