import assert from 'node:assert/strict'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { composeAgent, inputFingerprint, loadProfiles, renderTarget, runtimeRegistry } from '../profile-lib.mjs'
import { parseFlatYaml } from '../profile-format.mjs'
import { compareTargets } from '../profile-runtimes/shared.mjs'

const profiles = loadProfiles(fileURLToPath(new URL('../../', import.meta.url)))
const reviewer = profiles.find((p) => p.name === 'reviewer')
const claude = runtimeRegistry.get('claude')
const codex = runtimeRegistry.get('codex')
const kimi = runtimeRegistry.get('kimi')
const source = (path) => [{ name: 'architecture', path }]
const provenance = { kit: '4.0.0-alpha.4', inputs: 'abc' }

test('library profiles pin no model; both runtimes inherit by omission', () => {
  for (const profile of profiles) {
    const agent = composeAgent(profile)
    assert.equal(agent.claude.model, undefined, profile.name)
    assert.equal(agent.codex.model, undefined, profile.name)
    assert.doesNotMatch(renderTarget('claude', agent), /^model:/m)
    assert.doesNotMatch(renderTarget('codex', agent), /^model =/m)
  }
})

test('model availability belongs to the host: any current alias or ID is accepted', () => {
  assert.match(renderTarget('codex', composeAgent(reviewer, { codex: { model: 'gpt-6.1-sol' } })), /^model = "gpt-6.1-sol"$/m)
  assert.match(renderTarget('claude', composeAgent(reviewer, { claude: { model: 'opus' } })), /^model: "opus"$/m)
  assert.match(renderTarget('claude', composeAgent(reviewer, { claude: { model: 'inherit' } })), /^model: "inherit"$/m)
  assert.doesNotMatch(renderTarget('codex', composeAgent(reviewer, { codex: { model: 'inherit' } })), /^model =/m)
  assert.throws(() => codex.validate({ model: 'two\nlines' }, 'spec'), /invalid model/)
  assert.throws(() => claude.validate({ modle: 'opus' }, 'spec'), /unsupported field "modle"/)
})

test('YAML overlays and JSON project overrides normalize to the same types', () => {
  const overlay = parseFlatYaml('maxTurns: 20\nbackground: true\ntools: [Read, "Bash(git *)"]\nmodel: "claude-opus-5-5"', 'test')
  assert.deepEqual(overlay, { maxTurns: 20, background: true, tools: ['Read', 'Bash(git *)'], model: 'claude-opus-5-5' })
  claude.validate(overlay, 'test')
})

test('Codex skills.config points at SKILL.md', () => {
  const target = renderTarget('codex', composeAgent(reviewer, { skills: ['architecture'] }), source('/kit/skills/architecture/SKILL.md'))
  assert.match(target, /\[\[skills\.config\]\]\npath = "\/kit\/skills\/architecture\/SKILL.md"\nenabled = true/)
})

for (const runtime of [claude, codex, kimi]) {
  test(`${runtime.id}: diff separates path refresh, provenance, and behavior changes`, () => {
    const agent = composeAgent(reviewer, { skills: ['architecture'] })
    const base = runtime.parse(renderTarget(runtime.id, agent, source('/a/3.4.1/skills/architecture/SKILL.md'), 'x', provenance))
    const moved = runtime.parse(renderTarget(runtime.id, agent, source('/a/4.0.0/skills/architecture/SKILL.md'), 'x', provenance))
    assert.equal(compareTargets(base, moved).kind, 'paths')
    const bumped = runtime.parse(renderTarget(runtime.id, agent, source('/a/3.4.1/skills/architecture/SKILL.md'), 'x', { ...provenance, kit: '4.0.0' }))
    assert.equal(compareTargets(base, bumped).kind, 'provenance')
    const changed = runtime.parse(renderTarget(runtime.id, { ...agent, body: `${agent.body}\nNew duty.` }, source('/a/3.4.1/skills/architecture/SKILL.md'), 'x', provenance))
    const result = compareTargets(base, changed)
    assert.equal(result.kind, 'semantic')
    assert.match(result.changes.join('\n'), /profile behavior changed/)
    const narrowed = runtime.parse(renderTarget(runtime.id, composeAgent(reviewer, { skills: ['architecture'], access: 'full' }), source('/a/3.4.1/skills/architecture/SKILL.md'), 'x', provenance))
    assert.equal(compareTargets(base, narrowed).kind, 'semantic')
    if (runtime !== kimi) {
      const pinned = runtime.parse(renderTarget(runtime.id, composeAgent(reviewer, { skills: ['architecture'], [runtime.id]: { model: 'opus' } }), source('/a/3.4.1/skills/architecture/SKILL.md'), 'x', provenance))
      assert.match(compareTargets(base, pinned).changes.join('\n'), /model: \(inherit\/default\) → opus/)
    }
  })
}

test('3.4.1-format targets parse as an unknown baseline with their old settings', () => {
  const oldClaude = '---\nname: judy-security\ndescription: "Read-only review."\neffort: high\nmodel: opus\nskills: ["security"]\ntools: ["Read", "Edit", "Bash"]\n---\n\n<!-- Generated by agent-kit from .agent-kit/agents.json profile security. Do not edit by hand. -->\nYou are a reviewer.\n'
  const parsed = claude.parse(oldClaude)
  assert.equal(parsed.provenance, undefined)
  assert.equal(parsed.settings.model, 'opus')
  assert.equal(parsed.body, 'You are a reviewer.')
  const oldCodex = '# Generated by agent-kit from .agent-kit/agents.json profile security. Do not edit by hand.\nname = "judy-security"\ndescription = "Read-only review."\nmodel = "gpt-5.6-sol"\nmodel_reasoning_effort = "high"\nsandbox_mode = "read-only"\ndeveloper_instructions = "You are the project custom agent \\"judy-security\\", materialized from the Agent Kit profession profile \\"security\\".\\n\\nYou are a reviewer.\\n\\nBefore acting, read and follow these installed knowledge skills when relevant: security.\\n"\n\n[[skills.config]]\npath = "/old/3.4.1/skills/security/SKILL.md"\nenabled = true\n'
  const codexParsed = codex.parse(oldCodex)
  assert.deepEqual(codexParsed.skills, ['security'])
  assert.equal(codexParsed.body, 'You are a reviewer.')
  assert.equal(codexParsed.settings.model, 'gpt-5.6-sol')
})

test('input fingerprint ignores machine paths and tracks profile or recipe changes', () => {
  const spec = { name: 'reviewer', profile: 'reviewer' }
  assert.equal(inputFingerprint(reviewer, spec, 'claude'), inputFingerprint(reviewer, { ...spec }, 'claude'))
  assert.notEqual(inputFingerprint(reviewer, spec, 'claude'), inputFingerprint(reviewer, { ...spec, effort: 'low' }, 'claude'))
  assert.notEqual(inputFingerprint(reviewer, spec, 'claude'), inputFingerprint({ ...reviewer, body: `${reviewer.body}x` }, spec, 'claude'))
})

test('Kimi target: explicit allowlist by access, context restored on purpose, no model or effort fields', () => {
  const readOnly = renderTarget('kimi', composeAgent(reviewer), source('/kit/skills/architecture/SKILL.md'))
  const tools = readOnly.split('\n').find((line) => line.startsWith('tools: '))
  assert.doesNotMatch(tools, /"(?:Edit|Write|Bash|Agent|AgentSwarm)"/)
  assert.match(tools, /"Read"/)
  assert.doesNotMatch(readOnly, /^(model|effort):/m)
  for (const part of ['${agents_md}', '${skills}', '## Handoff', 'architecture: "/kit/skills/architecture/SKILL.md"']) assert(readOnly.includes(part), part)
  const full = renderTarget('kimi', composeAgent(reviewer, { access: 'full' }))
  assert.match(full, /"Bash"/)
  assert.doesNotMatch(full, /"Agent"/)
})

test('Kimi rejects profile text that its template engine would substitute', () => {
  const agent = composeAgent(reviewer)
  assert.throws(() => renderTarget('kimi', { ...agent, body: `${agent.body}\nUse \${cwd} here.` }), /template variable/)
  assert.doesNotThrow(() => renderTarget('kimi', { ...agent, body: `${agent.body}\nconst x = \`\${value}\`` }))
  assert.throws(() => kimi.validate({ model: 'k2' }, 'spec'), /unsupported field "model"/)
})
