#!/usr/bin/env bash

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
errors=0
checked=0

err() {
  printf 'ERROR [%s]: %s\n' "$1" "$2" >&2
  errors=$((errors + 1))
}

fm_field() {
  local file="$1" field="$2"
  awk -v f="$field" '
    BEGIN { in_fm=0 }
    /^---[[:space:]]*$/ { in_fm = !in_fm; next }
    in_fm && $1 == f ":" { sub(/^[^:]*:[[:space:]]*/, ""); print; exit }
  ' "$file"
}

bash "$repo_root/scripts/validate-plugin-manifests.sh"

if [[ -e "$repo_root/.claude/agents" || -e "$repo_root/.claude/skills" ]]; then
  err "packaging" "project-local .claude agents/skills must not be shipped by the plugin repository"
fi
if [[ -e "$repo_root/.agents/plugins/marketplace.json" ]]; then
  err "packaging" "use the shared .claude-plugin/marketplace.json instead of a duplicate .agents catalog"
fi

if ! command -v node >/dev/null 2>&1; then
  err "runtime" "node is required for profile and project-agent validation"
else
  node --check "$repo_root/scripts/profile-lib.mjs"
  node --check "$repo_root/scripts/generate-profiles.mjs"
  node --check "$repo_root/scripts/validate-codex-agent.mjs"
  node --check "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs"
  node "$repo_root/scripts/generate-profiles.mjs" --check
fi

profile_count=0
for profile_file in "$repo_root"/profiles/*/PROFILE.md; do
  profile=$(basename "$(dirname "$profile_file")")
  profile_count=$((profile_count + 1))
  [[ -f "$repo_root/profiles/$profile/claude.yaml" ]] || err "$profile" "missing claude.yaml"
  [[ -f "$repo_root/profiles/$profile/codex.yaml" ]] || err "$profile" "missing codex.yaml"
  [[ -f "$repo_root/.claude-plugin/agents/$profile.md" ]] || err "$profile" "missing generated Claude agent"
  [[ -f "$repo_root/skills/agent-orchestrator/references/profiles/$profile.md" ]] || err "$profile" "missing generated orchestrator reference"
done
printf 'Profile library OK: %d profile(s).\n' "$profile_count"

project_test_dir=$(mktemp -d)
collision_test_dir=$(mktemp -d)
trap 'rm -rf "$project_test_dir" "$collision_test_dir"' EXIT

mkdir -p "$project_test_dir/.agent-kit" "$project_test_dir/.claude/agents"
printf 'manual project agent\n' > "$project_test_dir/.claude/agents/manual.md"
jq -n '{
  schema_version: 1,
  agents: [
    {
      name: "backend-rust",
      profile: "backend",
      skills: ["backend", "api-design", "database", "rust"],
      runtimes: ["claude", "codex"],
      codex: {effort: "high"}
    },
    {
      name: "reviewer",
      profile: "reviewer",
      runtimes: ["codex"],
      access: "read-only"
    }
  ]
}' > "$project_test_dir/.agent-kit/agents.json"

node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" --project-root "$project_test_dir"
node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" --project-root "$project_test_dir" --check

jq '.note = "unsupported"' "$project_test_dir/.agent-kit/agents.json" > "$project_test_dir/.agent-kit/invalid-agents.json"
if node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" \
  --project-root "$project_test_dir" \
  --config "$project_test_dir/.agent-kit/invalid-agents.json" \
  --check >/dev/null 2>&1; then
  err "materializer" "accepted an unsupported top-level config field"
fi

[[ -f "$project_test_dir/.claude/agents/backend-rust.md" ]] || err "materializer" "Claude target missing"
[[ -f "$project_test_dir/.codex/agents/backend-rust.toml" ]] || err "materializer" "Codex backend target missing"
[[ -f "$project_test_dir/.codex/agents/reviewer.toml" ]] || err "materializer" "Codex reviewer target missing"
[[ ! -f "$project_test_dir/.claude/agents/reviewer.md" ]] || err "materializer" "runtime filtering failed"
[[ $(<"$project_test_dir/.claude/agents/manual.md") == "manual project agent" ]] || err "materializer" "manual agent was modified"

node "$repo_root/scripts/validate-codex-agent.mjs" "$project_test_dir"/.codex/agents/*.toml

grep -q 'sandbox_mode = "read-only"' "$project_test_dir/.codex/agents/reviewer.toml" || err "materializer" "read-only access did not reach Codex sandbox"
grep -q '\[\[skills.config\]\]' "$project_test_dir/.codex/agents/backend-rust.toml" || err "materializer" "Codex skill configuration missing"

mkdir -p "$collision_test_dir/.agent-kit" "$collision_test_dir/.claude/agents"
jq -n '{schema_version: 1, agents: [{name: "backend", profile: "backend", runtimes: ["claude"]}]}' > "$collision_test_dir/.agent-kit/agents.json"
printf 'owned by user; mentions Generated by agent-kit only as prose\n' > "$collision_test_dir/.claude/agents/backend.md"
if node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" --project-root "$collision_test_dir" >/dev/null 2>&1; then
  err "materializer" "overwrote or accepted a colliding non-generated agent"
fi

jq '.agents = [.agents[] | select(.name == "reviewer")]' "$project_test_dir/.agent-kit/agents.json" > "$project_test_dir/.agent-kit/agents.next.json"
mv "$project_test_dir/.agent-kit/agents.next.json" "$project_test_dir/.agent-kit/agents.json"
node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" --project-root "$project_test_dir" --prune
[[ ! -e "$project_test_dir/.claude/agents/backend-rust.md" ]] || err "materializer" "prune left obsolete Claude target"
[[ ! -e "$project_test_dir/.codex/agents/backend-rust.toml" ]] || err "materializer" "prune left obsolete Codex target"
[[ -f "$project_test_dir/.claude/agents/manual.md" ]] || err "materializer" "prune removed manual agent"
node "$repo_root/skills/agent-creator/scripts/materialize-agents.mjs" --project-root "$project_test_dir" --check
printf 'Project materialization OK: Claude, Codex, collision, drift, and prune cases.\n'

for file in "$repo_root"/skills/*/SKILL.md; do
  skill=$(basename "$(dirname "$file")")
  checked=$((checked + 1))

  if [[ $(head -n 1 "$file") != '---' ]]; then
    err "$skill" 'missing opening YAML frontmatter delimiter'
    continue
  fi

  name=$(fm_field "$file" name)
  description=$(fm_field "$file" description)
  user_invocable=$(fm_field "$file" user-invocable)
  line_count=$(wc -l < "$file" | tr -d ' ')

  if [[ -z "$name" ]]; then
    err "$skill" "missing name"
  elif [[ "$name" != "$skill" ]]; then
    err "$skill" "frontmatter name '$name' does not match directory"
  elif [[ ! "$name" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || (( ${#name} > 64 )); then
    err "$skill" "name must be lowercase kebab-case and at most 64 characters"
  fi

  if [[ -z "$description" ]]; then
    err "$skill" "missing single-line description"
  elif [[ "$description" = '|' || "$description" = '>' ]]; then
    err "$skill" "description must be a single line"
  elif (( ${#description} > 1024 )); then
    err "$skill" "description exceeds 1024 characters"
  fi

  if [[ -n "$user_invocable" && "$user_invocable" != 'true' && "$user_invocable" != 'false' ]]; then
    err "$skill" "user-invocable must be true or false"
  fi

  if (( line_count > 550 )); then
    err "$skill" "SKILL.md has $line_count lines; ceiling is about 550"
  fi

  if awk '
    BEGIN { in_fm=0 }
    /^---[[:space:]]*$/ { in_fm = !in_fm; next }
    in_fm && /^meta:[[:space:]]*/ { found=1 }
    END { exit found ? 0 : 1 }
  ' "$file"; then
    err "$skill" "unknown top-level meta field; use metadata"
  fi
done

if rg -n 'team-creator|team-orchestrator|agent-runner|\.claude/teams|scripts/generate-agents\.mjs|agents/[^/ ]+/AGENT\.md' \
  "$repo_root/AGENTS.md" "$repo_root/README.md" "$repo_root/skills" "$repo_root/scripts" \
  --glob '!validate-repository.sh' >/dev/null; then
  err "stale-reference" "removed team runtime or pre-profile agent path is still referenced"
fi

if command -v claude >/dev/null 2>&1; then
  claude plugin validate "$repo_root" --strict
else
  printf 'WARN: claude CLI not found; skipped native plugin validation.\n' >&2
fi

if (( errors > 0 )); then
  printf 'Repository validation failed: %d error(s).\n' "$errors" >&2
  exit 1
fi

printf 'Repository validation OK: %d skills checked.\n' "$checked"
